### ISSUE TITLE
The bot doesn't grab the Discord session ID

### ISSUE THREAD

**Issue by alexandra-love** [JasperVanEsveld/discordeno-audio-plugin#2]
Hi,
I've been working with your music player a bit and ran into a problem where it wouldn't send audio over Discord. I discovered the problem is that at least the way I'm using the bot, with a /play command that takes a url, any listeners that set the session ID aren't being fired. I fixed it by doing this:

in `/main.ts` of my bot:
```
let sessionId = "";
```
...
```
bot.events.ready = async function (bot, payload) {
	sessionId = payload.sessionId;
}
```
...
```
export function getSessionId() {
	return sessionId;
}
```

Then in `/src/mod.ts` of your audio player I added an import for `getSessionId` and `conn.connectInfo.sessionId = getSessionId();` to the `bot.events.voiceServerUpdate` function, after `conn` has been defined.

I'm sure there's a better way to do this, but I figured I'd let you know this is how I figured out how to work around the bug.

**Comment by JasperVanEsveld** [comment]
Hm interesting, so the event gets fired but the sessionId is incorrect or not there?
Could you add `console.log(event);` or `console.log(event.sessionId);` to `src/mod.ts` where you added `getSessionId();`?

Wonder what it gives you and if it is the same session id that you get from your function

**Comment by alexandra-love** [comment]
Sorry for the late response. I added `console.log(event)` right above where I'm calling `getSessionId()` and it returns the following:
```
{
  token: <token id that I've removed>,
  guildId: <guild_id>,
  endpoint: "stockholm589.discord.media:443"
}
```

**Comment by JasperVanEsveld** [comment]
Ah sorry, I now see you added it to the `voiceServerUpdate` which does not have a `sessionId`.
The one above in `voiceStateUpdate` should have it.
Which is triggered whenever the bot joins a voice channel after it has been started.

So what maybe happened is that the bot was already connected from the previous run and restarted
Right now the connection would not get filled with the `sessionId`
You could try to force it to connect after starting the bot to see if the `sessionId` does get set.

To be honest I thought that you just weren't able to reconnect after restarting, but maybe you could with the `sessionId` from `ready`
If that is the case, I could look into listening to ready as well to set the `sessionId`

**Comment by JasperVanEsveld** [comment]
Actually I am not sure what happens.
Because if `voiceServerUpdate` gets triggered I am pretty sure you connect normally.
Could you maybe do the same `console.log(event)` in `voiceStateUpdate`?
If it gets triggered at all it should contain the `sessionId`

**Comment by alexandra-love** [comment]
I'm not sure how to get `voiceStateUpdate` to fire. I had the bot join a voice channel, play some music, and then leave the channel, and it wasn't fired at any point.

**Comment by JasperVanEsveld** [comment]
Sorry for the late reaction
It might be an intent issue then, do you have `GuildVoiceStates` in your intents?

**Comment by alexandra-love** [comment]
That text isn't anywhere in my entire project, including your code. Where should I add it?

**Comment by JasperVanEsveld** [comment]
When creating your Discordeno bot you use `createBot()`.
Here you can add your intents with a `|` between them
```
createBot({
    token: BOT_TOKEN,
    botId: BOT_ID,
    intents: Intents.GuildVoiceStates | .. | .. ,
  })
```

I will update the example in the readme with this to make it a bit more obvious that it is required

**Comment by alexandra-love** [comment]
Oh, my bad. I'll take a look later today/tonight and get back to you.

**Comment by JasperVanEsveld** [comment]
You managed to try it out?

Btw, there are some newer versions of the plugin to fix some youtube playback issues.

**Comment by alexandra-love** [comment]
It did work, thank you. Sorry for being slow again, I was on vacation for two weeks.

**Comment by JasperVanEsveld** [comment]
Ah nice!
No worries, hope you had a nice vacation :)
